version: "3.9"

services:
  hugo:
    image: klakegg/hugo:ext-alpine
    command: server --bind 0.0.0.0 --baseURL http://localhost:1313 --watch --disableFastRender
    ports:
      - "1313:1313"
    volumes:
      - ./:/src
    environment:
      HUGO_ENV: development
    working_dir: /src
